urls.py
from django.conf.urls import patterns, url

from assessment import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='assessment_index'),
    url(r'^login/$', views.user_login, name='assessment_login'),
    url(r'^welcome/$', views.landing_page, name='assessment_landpage'),
    url(r'^logout/$', views.user_logout, name='assessment_logout'),
    url(r'^registration/$', views.user_registration, name='assessment_registration'),
    url(r'^users/$', views.user_list, name='assessment_users'),
    url(r'^users/(\d+)$', views.user_results, name='assessment_results'),
    url(r'^users/delete/(\d+)$', views.user_delete, name='assessment_deleteuser'),
    url(r'^surveys/$', views.SurveyListView.as_view(), name='assessment_surveys'),
    url(r'^surveys/(?P<slug>[-\w]+)/$', views.ResultCreateView.as_view(), name='assessment_survey'),
    url(r'^surveys/results/(?P<pk>\d+)/$', views.ResultDetailView.as_view(), name='survey_results'),
    url(r'^results/$', views.ResultListView.as_view(), name="result_list"),
    url(r'^results/(?P<slug>[-\w]+)/$', views.SurveyResultListView.as_view(), name="survey_result_list"),
    url(r'^user/(?P<pk>\d+)/results/$', views.UserResultListView.as_view(), name='user_results'),
    url(r'^authenticate/(?P<profile_token>.+)$', views.user_authenticate, name='assessment_authenticate'),
)

models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.signals import post_delete, post_save
from django.db.models.signals import class_prepared
from django.core.validators import MaxLengthValidator
from django.utils.translation import ugettext as _
from uuid import uuid4
from django.utils.text import slugify

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User


# allow longer username
def longer_username_signal(sender, *args, **kwargs):
    if sender.__name__ == "User" and sender.__module__ == "django.contrib.auth.models":
        patch_user_model(sender)
class_prepared.connect(longer_username_signal)

MAX_LENGTH = 200

def patch_user_model(model, fieldname):
    field = model._meta.get_field(fieldname)

    field.max_length = MAX_LENGTH
    field.help_text = _("Required, %s characters or fewer. Only letters, "
                        "numbers, and @, ., +, -, or _ "
                        "characters." % MAX_LENGTH)

    # patch model field validator because validator doesn't change if we change
    # max_length
    for v in field.validators:
        if isinstance(v, MaxLengthValidator):
            v.limit_value = MAX_LENGTH

# check if User model is patched
if User._meta.get_field("username").max_length != MAX_LENGTH:
    patch_user_model(User, "username")
    patch_user_model(User, "email")
    patch_user_model(User, "first_name")
    patch_user_model(User, "last_name")


class Survey(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255)
    insertion = models.CharField(max_length=200, blank=True)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now=False, default=datetime.datetime.now)
    external_survey_url = models.CharField(max_length=255, blank=True)
    minutes_allowed = models.FloatField(max_length=10, default=0)
    is_active = models.BooleanField(default=True)
    
    class Meta:
        app_label = 'assessment'
        ordering = ['pub_date']
        verbose_name = "Survey"
        verbose_name_plural = "Surveys"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('assessment:assessment_survey', kwargs={'slug': self.slug})
    
    def get_external_url(self):
        if 'https://' in self.external_survey_url or 'http://' in self.external_survey_url:
            return self.external_survey_url
        else:
            return False

    def save(self, *args, **kwargs):
        varprocs1 = [self.insertion]
        i = 0
        if self.insertion is not "":
            while i < 20:
                try:
                    self.description = self.description % tuple(varprocs1)
                except TypeError:
                    i += 1
                    varprocs1.append(self.insertion)
        self.slug = slugify(self.name)
        super(Survey, self).save(*args, **kwargs)


class SurveyImage(models.Model):
    survey = models.ForeignKey(Survey, related_name='images')
    image = models.ImageField(upload_to='assessment', blank=True)
    
    def __str__(self):
        return self.image.url


class Available(models.Model):
    user = models.ForeignKey(User)
    survey = models.ForeignKey(Survey)
    url = models.CharField(max_length=255)
    
    class Meta:
        app_label = 'assessment'
        unique_together = ('survey', 'user')


class Question(models.Model):
    TRUEFALSE = 1
    MULTICHOICE = 2
    TEXT = 3
    EXTERNAL = 4
    MULTISELECT = 5
    RANGE = 6
    DISPOSITION = 7

    QUESTION_TYPE = (
        (TRUEFALSE, 'True or False'),
        (MULTICHOICE, 'Multiple Choice'),
        (MULTISELECT, 'Multiple Select'),
        (TEXT, 'Text'),
        (EXTERNAL, 'External Survey'),
        (RANGE, 'Range'),
        (DISPOSITION, 'Disposition'),
    )

    survey = models.ForeignKey(Survey)
    page_number = models.DecimalField(max_digits=2, decimal_places=0, default=1)
    question_sum = models.IntegerField(max_length=25, blank=True, null=True)
    question_name = models.CharField(max_length=255)
    question = models.TextField()
    question_type = models.IntegerField(
        max_length=1,
        choices=QUESTION_TYPE,
        default=MULTICHOICE)

    class Meta:
        app_label = 'assessment'
        ordering = ['survey', 'id']
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'

    def __str__(self):
        return self.question

    def save(self, *args, **kwargs):
        varprocs1 = [self.survey.insertion]
        i = 0
        if self.survey.insertion is not "":
            while i < 20:
                try:
                    self.question = self.question % tuple(varprocs1)
                except TypeError:
                    i += 1
                    varprocs1.append(self.survey.insertion)
        if self.question_sum is None:
            self.question_sum = 100
        super(Question, self).save(*args, **kwargs)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_value = models.TextField(max_length=500)
    weight = models.FloatField(max_length=10, default=0)

    class Meta:
        app_label = 'assessment'
        ordering = ['id']
    
    def __str__(self):
        return self.choice_value

    def save(self, *args, **kwargs):
        varprocs1 = [self.question.survey.insertion]
        i = 0
        if self.question.survey.insertion is not "":
            while i < 20:
                try:
                    self.choice_value = self.choice_value % tuple(varprocs1)
                except TypeError:
                    i += 1
                    varprocs1.append(self.question.survey.insertion)
        super(Choice, self).save(*args, **kwargs)


class Result(models.Model):
    user = models.ForeignKey(User, related_name='results', editable=False)
    survey = models.ForeignKey(Survey, related_name='results', editable=False)
    started_on = models.DateTimeField(auto_now=False, editable=False)
    completed_on = models.DateTimeField(auto_now=True, default=datetime.datetime.now)
    excess_seconds = models.IntegerField(editable=False)
    score = models.CharField(max_length=10, default=0, editable=False)

    class Meta:
        app_label = 'assessment'
        unique_together = ('survey', 'user')

    def __str__(self):
        return "%s, %s" % (self.survey, self.user)

    def get_absolute_url(self):
        return reverse('assessment:survey_results', kwargs={'pk': self.id})


class Answer(models.Model):
    result = models.ForeignKey(Result, related_name='answers', editable=False)
    question = models.ForeignKey(Question, related_name='answers', editable=False)
    answer = models.TextField(blank=True, null=True)

    class Meta:
        app_label = 'assessment'
        ordering = ['result', 'question']
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'
    
    def __str__(self):
        return self.answer


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    gender = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    phone_number = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    job_title = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    job_department = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    job_location = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    company = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    assessment_protocol = models.CharField(max_length=MAX_LENGTH, blank=True, null=True)
    profile_token = models.CharField(max_length=MAX_LENGTH, blank=True, null=True, unique=True)

    def get_absolute_url(self):
        return reverse('assessment:assessment_results', args=(user.id,))

    def save(self, *args, **kwargs):
        if not self.id:
            self.profile_token = str(uuid4())
        super(UserProfile, self).save(*args, **kwargs)


def create_user_profile(sender, instance, **kwargs):
    try:
        UserProfile.objects.create(user=instance)
    except:
        pass


def delete_user_profile(sender, instance, **kwargs):
    try:
        UserProfile.objects.get(user=instance).delete()
    except:
        pass


post_save.connect(create_user_profile, sender=User)
post_delete.connect(delete_user_profile, sender=User)

templates/assessment/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'assessment/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'assessment/bootstrap-theme.min.css' %}" />
        {% block extra_css %}
        {% endblock extra_css %}
        <script src="{% static 'assessment/jquery-2.1.0.min.js' %}"></script>
        <script src="{% static 'assessment/bootstrap.min.js' %}"></script>
        <meta charset=utf-8 />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Assessment Automation System{% block titlebar %}{% endblock %}</title>
    </head>
    <body style="padding-top: 10em;">
        {% block topbar %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header navbar-brand">Assessment Automation System<small> {% block pagetitle %}{% endblock %}</small></div>
                <div class="pull-right">
                    <ul class="list-inline" style="margin-top: 1em;">
                        <li>{% block timer %}{% endblock %}</li>
                        {% if user.is_staff %}
                        <li><a href="{% url 'assessment:assessment_index' %}" class="btn btn-default">Index</a></li>
                        
                        <li><a href="{% url 'admin:index' %}" class="btn btn-warning">Admin</a></li>
                        
                        <li><a href="{% url 'assessment:assessment_logout' %}" class="btn btn-danger">Logout</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
        <div class='container-fluid'>
        <br>
        {% block content %}{% endblock %}
        </div>
        {% if referrer %}
        <div class="container-fluid">
            <a href="{{ referrer }}" class="btn btn-danger">Back</a>
        </div>
        {% endif %}
        <br>
    </body>
</html>

templates/assessment/base_index.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Index{% endblock %}
{% block pagetitle %}Index{% endblock %}

{% block content %}

<div class="well col-md-4">
    <a href="{{ profile }}" class="btn btn-info btn-block">Profile</a>
    <a href="{% url 'assessment:assessment_surveys' %}" class="btn btn-info btn-block">Surveys</a>
    {% if user.is_staff %}
     <a href="{% url 'assessment:assessment_users' %}" class="btn btn-info btn-block">Registry</a>
     <a href="{%url 'assessment:result_list' %}" class="btn btn-info btn-block">Results</a>
     <a href="{%url 'assessment:assessment_landpage' %}" class="btn btn-info btn-block">Welcome Page</a>
    {% endif %}
</div>

{% endblock %}

templates/assessment/base_landpage.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Welcome{% endblock %}
{% block pagetitle %}Welcome{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assessment/landpage.css"
      xmlns="http://www.w3.org/1999/html"/>
{% endblock extra_css %}

{% block content %}

<div class="container" id="bordered">
    <img src="{{STATIC_URL}}assessment/Carswell.jpg" id="first">
    <h4>Landing Page:</h4>
    <h5>{{ user.first_name }}:</h5>
    <p class="text">
        Welcome to Carswell's Assessment site. Today you’ll complete a variety of electronic
assessments over an encrypted connection and all of your data will be stored in a secured
database. The assessments you have filled out today have been picked for their relevance to the
position that you are applying for and will take up to 1 or 2 hours to complete.
    </p>
    <h4>Today you will be completing:</h4>
    <p>
        {% for assessment in assessments %}
            <li>{{ assessment }}</li>
        {% endfor %}
    </p>
    <h4>Directions:</h4>
    <p class="text">
        Once you click “Next” you will be forwarded to your assessment portal page. This page will
contain a list of your assessments on the left side, one button for each assessment that you are
to complete. Once you click on a button, you’ll be taken to that assessment. Simply fill out the
questions and then click “Finish”. This will take you back to the main portal site, and you’ll
see that assessment now shows up as completed. Keep going until all of your assessments are
marked as completed and show up in red on the right side of the page.
    </p>
    <p class="text">
Several assessments will forward you to a secured external page in order to fill out the survey.
To fill out these assessments, simply click the button that you are instructed to fill out and the
survey will open up in a new window. Just follow the instructions in that window and close it
when you are finished and then click “Finish” when you’re back to the assessment page. This
will mark it as complete and take you back to main portal where you can move on to the next
assessment.
    </p>
    <p class="text">
Once you are finished with all of your assessments, you can safely close the window.
    </p>
    <p class="text">
Some assessments may require you to come on site. If you have been assigned an assessment
such as this, we will contact you by phone or e-mail to setup an appointment.
    </p>
    <div class="row" id="buttonblock">
        <img src="{{STATIC_URL}}assessment/carswell-banner.jpg" id="second">
        </br>
        <a href="{{ profile }}" class="btn btn-primary btn-block">Next</a>
        </br>
    </div>
</div>

{% endblock %}

templates/assessment/base_login.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Login{% endblock %}
{% block pagetitle %}Login{% endblock %}
{% block topbarbuttons %}{% endblock %}

{% block content %}

<fieldset>
    <form action="{% url 'assessment:assessment_login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-success" />
    </form>
</fieldset>

{% endblock %}

templates/assessment/base_registration.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Registration{% endblock %}
{% block pagetitle %}Registration{% endblock %}

{% block content %}

{% if registered %}
<span class="bg-success">User registered.</span> <a href="{% url 'assessment:assessment_users' %}" class="btn btn-info">User List</a>
<br><br>
<div class="well"><strong>Login URL:</strong> <a href="{{ login_url }}">Login as User</a></div>
{% endif %}

<div class="well col-md-4">
    <fieldset>
        <form action="{% url 'assessment:assessment_registration' %}" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {% if user.is_staff %}
            <input type="submit" value="Register User" class="btn btn-success" />
            {% else %}
            <input type="submit" value="Update Profile" class="btn btn-success" />
            {% endif %}
        </form>
    </fieldset>
</div>

{% endblock %}

templates/assessment/base_resultlist.html
{% extends 'assessment/base.html' %}
{% block titlebar %}: Results{% endblock %}
{% block pagetitle %}Results{% endblock %}

{% block content %}

    <table class="table">
        <thead>
            <th>User Name</th>
            <th>Survey Name</th>
            <th>Date Completed</th>
            <th>Score</th>
        </thead>
        {% for result in result_list %}
        <tr>
            <td><a href="{% url 'assessment:user_results' result.user.id %}">{{ result.user.username }}</a></td>
            <td><a href="{{ result.get_absolute_url }}">{{ result.survey.name }}</a></td>
            <td>{{ result.completed_on }}</td>
            <td>{{ result.score }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/assessment/base_survey.html
{% extends "assessment/base.html" %}
{% load assessment_tags %}
{% block titlebar %}: {{ survey.name }}{% endblock %}
{% block pagetitle %}{{ survey.name }}{% endblock %}
{% block timer %}{% if seconds_allowed > 0 %}<div id="timer" style="padding: 5px; border-radius: 3px; background-color: #ff7777;"></div>{% endif %}{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}assessment/radio.css"/>
{% endblock extra_css %}
{% block content %}

{% if survey.images %}
    {% for image in survey.images.all %}
        <img src="{{ image }}"/>
    {% endfor %}
{% endif %}

{% if survey.minutes_allowed > 0 %}

<script type="text/javascript">
var count = {{ seconds_allowed }};

var counter = setInterval(timer, 1000);

function timer(){
    count = count - 1;
    if(count <= 0){
        clearInterval(counter);
        $("form").submit();
        return;
    }

    var seconds = Math.floor(count);
    var minutes = Math.floor(seconds / 60);
    seconds -= minutes*60;
    if(minutes < 10){minutes = "0" + minutes;}
    if(seconds < 10){seconds = "0" + seconds;}
    
    if(count == 500){
        alert("5 minutes remaining...");
    }

    document.getElementById("timer").innerHTML = '<strong>Time remaining:</strong> ' +  minutes + ':' + seconds;
}
</script>

{% endif %}

<div class="container">
    <div class="page-header">
        <h1>{{ survey.name }}</h1>
        <p>{{ survey.description|linebreaks }}</p>
    </div>

    {% if survey.external_survey_url or external_url %}

    <div class="container">
        <div class="well col-md-4">
            {% if external_url %}
            <a id="externalsurvey" class="btn btn-primary btn-lg btn-block" href="#" data-url="{{ external_url }}">Display External Survey</a>
            {% else %}
            <a id="externalsurvey" class="btn btn-primary btn-lg btn-block" href="#" data-url="{{ survey.external_survey_url }}">Display External Survey</a>
            {% endif %}
        </div>
    </div>
    <script type="text/javascript">
        var popup_width = $(window).width() * 0.9
        var popup_height = $(window).height() * 0.9
        
        $('#externalsurvey').on('click', function(e){
        var url = $(this).data('url');
    window.open(url, '_blank', 'location=yes,height=' + popup_height + ',width=' + popup_width + ',scrollbars=yes,status=yes');
        });
    </script>

    {% endif %}

    <form id="survey-form" action="." method="post">{% csrf_token %}
        {% for field, question in survey_form %}
        <div class="row">
            <div class="col-md-3"><strong>{{ question|linebreaks }}</strong></div>
            <div class="col-md-9">
                {% if question.question_type == 1 or question.question_type == 2 or question.question_type == 5 %}
                    {% for choice in form.visible_fields %}
                        {% if question.question_name in choice.help_text %}
                            <label style="float: left; width: auto; padding-right: 1.5em; padding-left: 1.5em;">
                                {{ choice }}
                            </label>
                        {% endif %}
                    {% endfor %}
                {% elif question.question_type == 6 %}
                    <table class="radiotable">
                        {% for choice in form.visible_fields %}
                            {% if question.question_name in choice.help_text %}
                                {% for field in choice %}
                                <tr>
                                    <td>
                                        {{ field.tag }}
                                    </td>
                                    <td>
                                        {{ field.choice_label|linebreaks }}
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </table>
                {% elif question.question_type == 7 %}
                    <table class="dispositiontable">
                        {{ form.non_field_errors }}
                        {% for choice in form.visible_fields %}
                            {% if question.question_name in choice.help_text %}
                            <tr>
                                <th>
                                    {{ choice.label }}
                                </th>
                                <td>
                                    {{ choice }}
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                {% elif question.question_type == 3 %}
                    {% for choice in form.visible_fields %}
                            {% if question.question_name in choice.help_text %}
                                {{ choice }}
                            {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <hr>
        {% endfor %}
        <br>
        <div class="row">
            <input type="submit" value="Finish" class="btn btn-lg btn-warning btn-block" onclick="return confirm('Are you sure?')" />
        </div>
    </form>
</div>

{% endblock content %}

templates/assessment/base_surveylist.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Surveys{% endblock %}
{% block pagetitle %}Surveys{% endblock %}

{% block content %}

{% if incomplete_available or user_results %}

<div class="well col-md-4">
    <h4>Surveys</h4>
    {% for survey in incomplete_available %}
        <a href="{{ survey.get_absolute_url }}" class="btn btn-info btn-block">{{ survey.name }}</a>
    {% endfor %}
    {% if not incomplete_available %}
        <span><strong class="bg-warning">No remaining surveys to complete.</strong></span>
    {% endif %}
</div>
<div class="col-md-offset-1 well col-md-4">
    <h4>Completed</h4>
    {% for result in user_results %}
    <a href="{{ result.get_absolute_url }}" class="btn btn-danger btn-block">{{ result.survey.name }} - {{ result.completed_on }}</a>
    {% endfor %}
    {% if not user_results %}
        <span><strong class="bg-warning">No surveys completed.</strong></span>
    {% endif %}
</div>

{% else %}
    <span><strong class="col-md-offset-1 bg-warning">No surveys available.</strong></span>
{% endif %}

{% endblock %}

templates/assessment/base_surveyresult.html
{% extends 'assessment/base.html' %}
{% block titlebar %}: Results{% endblock %}
{% block pagetitle %}Results{% endblock %}
{% block content %}

<div class="page-header">
  <p><strong>Survey Name: {{ result.survey }}</strong></p>
  <p><em>Answered by: {{ result.user }}</em></p>
  {% if user.is_staff %}
  <p><em>Score: {{ result.score }}</em></p>
  {% endif %}
  {% if result.excess_seconds > 0 %}
  <p><em>{{ result.excess_seconds }} seconds over time limit</em></p>
  {% endif %}
</div>

<div class="container">
    <table class="table">
        <thead>
            <th>Question</th>
            <th>Answer</th>
        </thead>
        {% for answer in result.answers.all %}
        <tr>
            <td>{{answer.question }}</td>
            <td>{{ answer }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

templates/assessment/base_surveyresultlist.html
{% extends 'assessment/base.html' %}

{% block content %}
  <table class="table">
    <tr>
      <th>User Name</th>
      <th>Date Completed</th>
      <th>Score</th>
    </tr>
    {% if len(results) > 0 %}
    {% for result in results %}
      <tr>
          <td><a href="{{ result.get_absolute_url }}">{{ result.user.username }}</a></td>
          <td>{{ result.completed_on }}</td>
          <td>{{ result.score }}</td>
      </tr>
    {% endfor %}
    {% endif %}
  </table>
{% endblock %}

templates/assessment/base_user.html
{% extends "assessment/base.html" %}
{% block titlebar %}: User{% endblock %}
{% block pagetitle %}User{% endblock %}

{% block content %}

{% if userinfo %}

{% if updated %}
<span class="bg-success">Updated.</span>
<br><br>
{% endif %}
<div class="container">
    <div class="well col-md-4">
        <fieldset>
            <form action="{{ post_url }}" method="post">
                {% csrf_token %}
                {{ user_form.as_p }}
                <input type="submit" value="Update" class="btn btn-success" />
            </form>
        </fieldset>
    </div>
    <div class=" col-md-1"></div>

    {% if userinfo.results.all %}
    <div class="well col-md-7">
        <table class="table table-hover table-condensed table-responsive">
            <thead>
                <tr>
                    <th>Test</th>
                    <th>Date</th>
                    {% if user.is_staff %}
                    <th>Score</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for result in userinfo.results.all %}
                <tr onclick="window.document.location='{{ result.get_absolute_url }}';">
                    <td>{{ result.survey }}</td>
                    <td>{{ result.completed_on }}</td>
                    {% if user.is_staff %}
                    <td>{{ result.score }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

</div>

<div class="container">
    {% if user.is_staff and userinfo.id != user.id %}

    <a href="{% url 'assessment:assessment_deleteuser' userinfo.id %}" class="btn btn-warning">Delete User</a>
    <div><br></div>
    <div class="well"><strong>Login URL:</strong> <a href="{{ login_url }}">Login as User</a></div>

    {% endif %}
</div>

{% if surveys_next %}
<div class="container">
    <a href="{% url 'assessment:assessment_surveys' %}" class="btn btn-primary btn-block">Next</a>
</div>
{% endif %}

{% else %}

<span><strong class="bg-warning">User not found.</strong></span>

{% endif %}

{% endblock %}

templates/assessment/base_userresults.html
{% extends 'assessment/base.html' %}
{% block titlebar %}: User Results{% endblock %}
{% block pagetitle %}User Results{% endblock %}

{% block content %}

<table class="table">
<tr>
    <th>Survey Name</th>
    <th>Date Completed</th>
    <th>Score</th>
</tr>
{% for result in results %}
    <tr>
        <td><a href="{{ result.get_absolute_url }}">{{ result.survey.name }}</a></td>
        <td>{{ result.completed_on }}</td>
        <td>{{ result.score }}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}

templates/assessment/base_users.html
{% extends "assessment/base.html" %}
{% block titlebar %}: Registry{% endblock %}
{% block pagetitle %}Registry{% endblock %}

{% block content %}

<div class='container-fluid'>
    <div class="well col-md-4">
        <a href="{% url 'assessment:assessment_registration' %}" class="btn btn-info btn-block">Register New User</a>
    </div>
</div>

{% if users %}
<table class="table table-hover table-condensed table-responsive">
    <thead>
        <tr>
            <th>Name</th>
            <th>E-mail Address</th>
            <th>Company</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr onclick="window.document.location='{{ user.id }}';">
            <td>{{ user.last_name }}, {{ user.first_name }}</td>
            <td>{{ user.email }}</td>
            <td>{% with user.userprofile_set.all|first as profile %} {{ profile.company }} {% endwith %}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}

<span><strong class="col-md-offset-1 bg-warning">No users/test-takers are registered.</strong></span>

{% endif %}

{% endblock %}